name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Cache Yarn local cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-local-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-local-cache-${{ runner.os }}-

      - name: Install dependencies
        shell: bash
        run: |
          corepack enable yarn
          yarn -v
          yarn install --immutable

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build
