name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Yarn local cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-local-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-local-cache-${{ runner.os }}-

      - name: Install dependencies
        run: |
          corepack enable yarn
          yarn install --immutable

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in ${{ github.ref_name }}

            See the [CHANGELOG](https://github.com/quangdatv/rosella-cli/blob/main/CHANGELOG.md) for details.

            ### Installation
            ```bash
            npm install -g rosella-cli@${{ steps.get_version.outputs.VERSION }}
            ```

            Or with yarn:
            ```bash
            yarn global add rosella-cli@${{ steps.get_version.outputs.VERSION }}
            ```
          draft: false
          prerelease: false
